---
- name: set unit number
  set_fact: unit_number={{ disk_param.0 | int + 1 }}

- name: fdisk device
  parted: 
    device : "{{ disk_param[1].device }}"
    number: 1
    state: present
    flags: ["lvm"]

- name: check pv
  shell: pvdisplay | grep "{{ disk_param[1].device }}1"
  register: pv_exists
  ignore_errors: true

- name: debug
  debug:
    var: pv_exists

- name: create PV
  shell: pvcreate "{{ disk_param[1].device }}1" 
  when: pv_exists.rc == 1

- name: create VG
  lvg:
    pvs: "{{ disk_param[1].device }}1" 
    vg: "{{ disk_param[1].vg }}"
    state: present

- name: Create lvm 
  lvol: 
    vg: "{{ disk_param[1].vg }}"
    lv: "{{ disk_param[1].lv }}"
    size: 100%FREE

- name: make file system (xfs)
  filesystem: 
    fstype: xfs 
    dev: "/dev/{{ disk_param[1].vg }}/{{ disk_param[1].lv }}"

- name: make mount point
  file: 
    path: "{{ disk_param[1].mountpoint }}" 
    state: directory

- name: mount disk
  mount: 
    src: "/dev/{{ disk_param[1].vg }}/{{ disk_param[1].lv }}" 
    fstype: xfs 
    path: "{{ disk_param[1].mountpoint }}"
    opts: defaults 
    state: mounted
