---
##################################################
# Description
#------------------------------------------------- 
#
#  parameters
#    disk_param
#      size       : disk size
#      device     : device name
#      mountpoint : mount point 
#      vg         : VG name
#      lv         : LV name
#
##################################################

- name: set unit number
  set_fact: unit_number={{ disk_param.0 | int + 1 }}

- name: Check before add disk 
  ignore_errors: true 
  shell: fdisk -l |grep "{{ disk_param[1].device }}1"
  args:
    executable: /bin/bash
  register: check_disk

- name: Checking result before setup linux Server
  fail:
    msg: "TARGET SERVER HAS DISK PARTITION!! JOB WAS CANCELLED!!"
  when: check_disk.rc == 0

- name: Create partition by fdisk command
  parted: 
    device : "{{ disk_param[1].device }}"
    number: 1
    state: present
    flags: ["lvm"]

- name: Create physical volume (PV)
  shell: pvcreate "{{ disk_param[1].device }}1" 

- name: Create volume group (VG)
  lvg:
    pvs: "{{ disk_param[1].device }}1" 
    vg: "{{ disk_param[1].vg }}"
    state: present

- name: Create logical volume (LV)
  lvol: 
    vg: "{{ disk_param[1].vg }}"
    lv: "{{ disk_param[1].lv }}"
    size: 100%FREE

- name: Make file system (xfs)
  filesystem: 
    fstype: xfs 
    dev: "/dev/{{ disk_param[1].vg }}/{{ disk_param[1].lv }}"

- name: Make mount point
  file: 
    path: "{{ disk_param[1].mountpoint }}" 
    state: directory

- name: Mount disk
  mount: 
    src: "/dev/{{ disk_param[1].vg }}/{{ disk_param[1].lv }}" 
    fstype: xfs 
    path: "{{ disk_param[1].mountpoint }}"
    opts: defaults 
    state: mounted


